# CI Script used for ABP iOS

stages:
  - test

cache:
  paths:
    - Carthage

build_code:
  stage: test
  before_script:
    - npm install
    - carthage update --platform ios --no-use-binaries --cache-builds
  script:
    - set -o pipefail && xcodebuild -verbose clean test -project KittCore.xcodeproj -scheme KittCore -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3'
  tags:
    - ios, abbcore