# CI Script used for Adblock Browser Core

stages:
  - unit_tests

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - rm -rf ../adblockbrowserios
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/eyeo/adblockplus/adblockbrowserios.git ../adblockbrowserios
  - cd ../adblockbrowserios
  - git checkout -b develop origin/develop
  - carthage update
  - cd ../adblockbrowserios-core
  - gem install bundler
  - bundle install
  - npm install

unit_tests:
  tags:
    - ios, abbcore
  stage: unit_tests
  script:
    - bundle exec fastlane ios tests
  artifacts:
    paths:
      - fastlane/tests/
  allow_failure: false
