# CI Script used for ABP iOS

stages:
  - test

build_code:
  stage: test
  before_script:
    - npm install -g jq
    - npm install
  script:
    - set -o pipefail && xcodebuild -verbose clean test -project KittCore.xcodeproj -scheme KittCore -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3'
    - set -o pipefail && xcodebuild -verbose clean test -project KittCore.xcodeproj -scheme KittCore -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.3.1'
    - set -o pipefail && xcodebuild -verbose clean test -project KittCore.xcodeproj -scheme KittCore -destination 'platform=iOS Simulator,name=iPhone 6s Plus,OS=9.3'
  tags:
    - ios, abbcore